### ISSUE TITLE
Point incursion-roguelike.net at this repo and a placeholder web site

### ISSUE THREAD

**Issue by rmtew** [rmtew/incursion-roguelike#10]
- [x] Needs placeholder web site made.
- [x] Go into DNS provider and point the domain here and have github letsencrypt or whatever an SSL certificate.

**Comment by HexDecimal** [comment]
GitHub Pages would be able to host the files from `website/` if you go that route.

**Comment by HexDecimal** [comment]
Repo settings -> Pages -> branch `master` -> folder `website`.

Should host the local webpage at https://rmtew.github.com/incursion-roguelike

**Comment by rmtew** [comment]
Lol. Nothing ever works. It won't let me select website. I'll faff around with it.

**Comment by HexDecimal** [comment]
The files at `website` could be moved to a new branch then with them at the root.

**Comment by rmtew** [comment]
Doing that as we post :-) Seems like the best option.

**Comment by rmtew** [comment]
We're live: https://incursion-roguelike.net/

**Comment by HexDecimal** [comment]
Remember to set the URL on the repo.

**Comment by rmtew** [comment]
How do you mean?

**Comment by rmtew** [comment]
Oh right! :-)

**Comment by HexDecimal** [comment]
Main repo page, about section. Maybe also set the description and tags.

**Comment by rmtew** [comment]
Done.
