### ISSUE TITLE
Standard integer types

### ISSUE THREAD

**Issue by HexDecimal** [rmtew/incursion-roguelike#2]
Int types are manually defined here:

https://github.com/rmtew/incursion-roguelike/blob/5d1c41549dad89fc756233fed22055347a5488ea/inc/Defines.h#L28-L33

These should be replaced with C99 `<stdint.h>` types or `<cstdint>` if the program is mostly C++.

Generally the use of `long` should be discouraged since it's the one that has an inconsistent size across platforms. `long` variables should be replaced by `int` if a specific size isn't desired.

**Comment by rmtew** [comment]
Agreed on stdint.h.

Anyone who changes this should be prepared for conflicting assumptions made by Julian or the authors of various antique dependencies back in the day when larger pointers or whatever were not even on the horizon. But I agree and I would have made this change yesterday had I been confident it wouldn't obstruct the shortest path to building a running executable.

**Comment by HexDecimal** [comment]
I've had to deal with this while maintaining libtcod. Pointer size assumptions obliterated libtcod's TCODZip functionality. Luckily most of these standard types should be relatively safe to update.

Since you've already got it working on x64 you must've already encountered and fixed errors based on pointer size. Type conversion warnings should be able to detect more of those kinds of issues if they're enabled.

**Comment by rmtew** [comment]
If the effect on x86 compilation is that it is not affected by underlying type size changes with the transition to stdint.h types, then this is safe enough to make. x64 runs. No-one has played it, I've given it cursory testing. But where the problems are most likely to lie are in the VM and similar places. And maybe in the other custom stuff Julian wrote. 

x64 running enough to create a character and enter game is as much testing as anyone ever gave it, and I am probably the only one who has.

**Comment by HexDecimal** [comment]
I forget where I last saw this. `long` is usually `int32` on all platforms except for Linux which is `int32` or `int64` depending on the target architecture.
