### ISSUE TITLE
DaysPassed overflows an array if the player has put more than 2048 items in a level

### ISSUE THREAD

**Issue by rmtew** [rmtew/incursion-roguelike#27]
Popo McTroll reports:
> I'm not sure if this is the right place to post about a bug, but twice so far I've had level 9 Rangers try to go downstairs to the 6th floor but the game crashes every time I try it. I suspect it might be because I hoard a lot of arrows and I rest a lot, so the game gets overloaded, so to speak. It also sometimes crashes when I try to rest.

And adds on inquiry:
> I was using version 0.6.9Y19.
> Executable just exits.

Debugging against the old debug binaries of 0.6.9Y19 is problematic as the source files do not match my tag. We should preserve the source code and binaries together as a build artifact and just make it a one step debugging process. It is however close enough to work out what is wrong.

![image](https://github.com/user-attachments/assets/f6e64c9b-341a-4572-8490-979836017d13)

Popo has accrued 3665 objects in the level he is leaving. The code crashes around 2071.

[SaveGame-0.6.9Y19.zip](https://github.com/user-attachments/files/16706740/SaveGame-0.6.9Y19.zip)

**Comment by HexDecimal** [comment]
An overflow of `Map::Things`?

https://github.com/rmtew/incursion-roguelike/blob/c77baf58d0ae41d65cc3eedd6afa665351294b57/inc/Map.h#L184

I think `NArray` is supposed to be a NULL terminated array. Something may have invalidated this array somewhere else, overwriting the terminator instead of appending to the array.

That is my best guess.

**Comment by rmtew** [comment]
No, NArray auto-extends. This is the stack variable `list` with 2048. Things.Count was at 3066.

**Comment by rmtew** [comment]
To be more correct `c` made it to 3066 at line 252. The crash was when `j` reached 2071 at 259 I think.

**Comment by HexDecimal** [comment]
I see it now. I followed the wrong thread.

This would be simple to fix by replacing `list`'s stack allocation with a `std::vector`.

Maybe this?
```cpp
auto list = std::vector<Thing>(Things.Count + 1);
```
Could also verify bounds with `.at` syntax.

**Comment by rmtew** [comment]
I don't know. If it were up to me I would do minimal changes and focusing on it getting it working. I would slap an alloca in there :-)

If you want to fix it that way go for it.

**Comment by HexDecimal** [comment]
I'll make a PR. `alloca` is not safe for this.

**Comment by rmtew** [comment]
Not safe? I doubt the stack size ever grows near 5%. This function alone on 64 bit is only 18664 bytes of stack usage. Negligibly larger than the 32 bit stack size which it would have been for most of the past 25 years.

**Comment by rmtew** [comment]
In any case, the acceptance criteria for whatever fix is made being merged is that it is tested in a way that verified it works. Ideally whoever does it would debug it and visually verify it works correctly, given the lack of any unit testing ability.

**Comment by HexDecimal** [comment]
I'll load the save file and go down the stairs.

**Comment by HexDecimal** [comment]
I've made some progress but I'm running into various unrelated errors. I suspect that save files expect a corresponding `gallery.dat` file.

**Comment by rmtew** [comment]
Are you sure the save file is useful for this in any way? It's for
0.6.9Y19. I think you need to play and rest or something until a day passes.

**Comment by rmtew** [comment]
In reflection that was ambiguous. The 32 bit 0.6.9Y19 built with VS2013 or
2015 and a much older platform SDK and so on. The version number being the
same in github is an illusion IMO

**Comment by rmtew** [comment]
fd9cff118da58fd607f8adc357d6851dabcd16fa

**Comment by HexDecimal** [comment]
I thought my current issue seemed to be about saves not generally being portable rather than changes in the save format.

I'll just point out what happened:

https://github.com/rmtew/incursion-roguelike/blob/c77baf58d0ae41d65cc3eedd6afa665351294b57/src/Create.cpp#L866-L872

`sz = 2`, so `ri` has 2 items, then `GallerySlot = 11` is out of bounds.
