### ISSUE TITLE
Reproducible yygram.cpp

### ISSUE THREAD

**Issue by HexDecimal** [rmtew/incursion-roguelike#31]
`src/yygram.cpp` is generated with lines like this:

https://github.com/rmtew/incursion-roguelike/blob/ef4120a8141f83645c765b8feedc08486b3e99c5/src/yygram.cpp#L199

But the project directory path makes this file not reproducible, they should be like this instead:

```cpp
# line 200 "../src/yygram.cpp"
```

I'm not sure how to fix this other than to make a Python script which can't be easily added to the build process.

Once this is fixed this command can be added to the CI to run after the build process to verify that these files were reproduced exactly:

```sh
git diff --exit-code src/tokens.cpp src/yygram.cpp inc/yygram.h
```

**Comment by HexDecimal** [comment]
Can also be fixed with a regular expression which is supported by standard C++.

**Comment by rmtew** [comment]
I have two observations..

Remember we build the parser generator that generates this code so we do not need external tools or post-processing to correct the line numbers. We build `modaccent` to take `grammar.acc` and generate our IncursionScript compiler. The point is that we control the line number generation.

https://github.com/rmtew/incursion-roguelike/blob/ef4120a8141f83645c765b8feedc08486b3e99c5/modaccent/src/actions.c#L2487

Additionally read what the line number says. This has been bothering me for a while but I kind of lumped it in with the black hole that the lexing and parsing that should be ignored. We are giving its own file name, the destination file name, not the source one (`grammar.acc`).

```c
# line 200 "../src/yygram.cpp"
```

I'll double check all this and make sure we are doing the modaccent integration right. There's only a couple of files.

**Comment by rmtew** [comment]
No the line numbers are right. I don't understand this obviously.

**Comment by rmtew** [comment]
The line numbers that are broken are in `modaccent` in files like `yylex.c` due to the renaming of files in the upstream project. In an ideal world we'd replace it with the upstream version, keep more of the referenced source files and stop the renaming. But that's kind of in the zone of replace modaccent/the vm/incursionscript with something else for time considerations.
